route:
  receiver: 'slack-lower-env-alerts'  
  group_wait: 10s
  group_interval: 30s
  routes:
  - receiver: 'slack-lower-env-alerts'
    matchers:
    - env=~"dev|staging"
  - receiver: 'slack-prod-env-alerts'
    matchers:
    - env=~"prod.*"

receivers:
  - name: 'slack-lower-env-alerts'
    slack_configs:
     - channel: '#lower-env-alerts'
       send_resolved: true
       api_url: 'https://hooks.slack.com/services/CHANGEME'
       icon_url: https://avatars3.githubusercontent.com/u/3380462
       title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
       text: >-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

        *Description:* {{ .Annotations.description }}

        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}         
  - name: 'slack-prod-env-alerts'
    slack_configs:
     - channel: '#alerts'
       send_resolved: true
       api_url: 'https://hooks.slack.com/services/CHANGEME'         
       icon_url: https://avatars3.githubusercontent.com/u/3380462
       title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
       text: >-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
   
        *Description:* {{ .Annotations.description }}
   
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
